### ISSUE TITLE
400 error when I try to store base64 string

### ISSUE THREAD

**Issue by DmitriyDmytruk** [NoelDeMartin/soukai-solid#12]
I want to store base64 string in solid pod. But when I try to execute I get the following error.
As I understood it has to do with the length of the string. Is there any way to get around this?
```
export default class Block extends SolidModel {
    static rdfContexts = {
        'hdf': DICTIONARY
    }

    static rdfsClasses = [
        'hdf:Block'
    ]

    static addRdfsClasses: string[] = []

    static fields = {
        type: FieldType.String,
        content: FieldType.String,
    }

export default class Screenshot extends Block {
    static type: string = 'screenshot';
}

let screenshot = new Screenshot({content: base64String, type: Screenshot.type})
screenshot.save(<link_to_inrupt_account>)
```

First log
```
Fetcher.ts:73 PATCH https://<...>.inrupt.net/hypercube/8f501a2f-e9f1-45e9-8da1-9a5f3021eda1 400 (Bad Request)
fetch @ Fetcher.ts:73
handle @ DpopAuthenticatedFetcher.ts:86
async function (async)
handle @ DpopAuthenticatedFetcher.ts:70
handle @ AggregateHandler.ts:79
async function (async)
handle @ AggregateHandler.ts:77
handle @ AutomaticRefreshFetcher.ts:53
fetch @ AuthFetcher.ts:75
fetch @ index.ts:86
async function (async)
fetch @ index.ts:85
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
Ht @ soukai-solid.esm.js:1
fetch @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
Ht @ soukai-solid.esm.js:1
t.createNonContainerDocument @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
Ht @ soukai-solid.esm.js:1
t.createDocument @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
u @ soukai-solid.esm.js:1
Promise.then (async)
s @ soukai-solid.esm.js:1
u @ soukai-solid.esm.js:1
Promise.then (async)
s @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
oe @ soukai-solid.esm.js:1
t.create @ soukai-solid.esm.js:1
n @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
Ct @ soukai-solid.esm.js:1
e.syncDirty @ soukai-solid.esm.js:1
(anonymous) @ soukai.esm.js:1
(anonymous) @ soukai.esm.js:1
(anonymous) @ soukai.esm.js:1
(anonymous) @ soukai.esm.js:1
U @ soukai.esm.js:1
t.save @ soukai.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
Ct @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
Ct @ soukai-solid.esm.js:1
e.withCollection @ soukai-solid.esm.js:1
e.save @ soukai-solid.esm.js:1
takeScreenshot @ Transcription.tsx:38
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
Show 51 more frames
```
Second log
```
soukai.esm.js:1 Uncaught (in promise) SoukaiError: Error creating document at https://<...>.inrupt.net/hypercube/8f501a2f-e9f1-45e9-8da1-9a5f3021eda1, returned 400 status code
    at new SoukaiError (http://127.0.0.1:3000/static/js/2.chunk.js:203161:19)
    at t.assertSuccessfulResponse (http://127.0.0.1:3000/static/js/2.chunk.js:201958:53)
    at t.<anonymous> (http://127.0.0.1:3000/static/js/2.chunk.js:201744:43)
    at http://127.0.0.1:3000/static/js/2.chunk.js:201444:21
    at Object.next (http://127.0.0.1:3000/static/js/2.chunk.js:201456:12)
    at u (http://127.0.0.1:3000/static/js/2.chunk.js:201345:17)
SoukaiError @ soukai.esm.js:1
t.assertSuccessfulResponse @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
(anonymous) @ soukai-solid.esm.js:1
u @ soukai-solid.esm.js:1
Promise.then (async)
takeScreenshot @ Transcription.tsx:38
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```
Get request
![image](https://user-images.githubusercontent.com/62432498/112273287-d8c10700-8c85-11eb-814e-e3d0254c9649.png)
Patch request
![image](https://user-images.githubusercontent.com/62432498/112273386-f55d3f00-8c85-11eb-9471-341eabaf470b.png)

**Comment by NoelDeMartin** [comment]
@DmitriyDmytruk Hey, it seems like you've opened a new issue: #13 Does it mean that you've fixed this one? Or is it still a problem?

**Comment by DmitriyDmytruk** [comment]
It's wasn't a problem, sorry)
